config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users
  resources :comments, only: [:new, :create]
  resources :tareas
  resources :materia
  resources :estados
  root to: "tareas#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tarea.rb
class Tarea < ApplicationRecord
  belongs_to :materium
  belongs_to :estado
  belongs_to :project
  has_many :comments, :dependent => :delete_all
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tarea, only: [:show, :edit, :update, :destroy]

  # GET /tareas
  # GET /tareas.json
  def index
    @proyecto = Project.find(session[:current_project])
    @tareas = Tarea.where(project_id: session[:current_project])
    @materias = Materium.all
    @estados = Estado.all
  end

  # GET /tareas/1
  # GET /tareas/1.json
  def show
  end

  # GET /tareas/new
  def new
    @tarea = Tarea.new
    @tarea.project_id = session[:current_project]
    @materias = Materium.all
    @estados = Estado.all
  end

  # GET /tareas/1/edit
  def edit
    @materias = Materium.all
    @estados = Estado.all
    @comment = Comment.new
    @tarea = Tarea.find(params[:id])
    @comentarios = @tarea.comments.page(params[:page]).per(10)
  end

  # POST /tareas
  # POST /tareas.json
  def create
    @tarea = Tarea.new(tarea_params)

    respond_to do |format|
      if @tarea.save
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @tarea }
      else
        format.html { render :new }
        format.json { render json: @tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tareas/1
  # PATCH/PUT /tareas/1.json
  def update
    respond_to do |format|
      if @tarea.update(tarea_params)
        format.html { redirect_to edit_tarea_path(@tarea.id), notice: 'Tarea was successfully updated.' }
        format.json { render :show, status: :ok, location: @tarea }
      else
        format.html { render :edit }
        format.json { render json: @tarea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tareas/1
  # DELETE /tareas/1.json
  def destroy
    @tarea.destroy
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tarea
      @tarea = Tarea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tarea_params
      params.require(:tarea).permit(:descripcion, :materium_id, :estado_id, :FechaFin, :project_id)
    end
end

app/helpers/tareas_helper.rb
module TareasHelper
end

app/views/tareas/_form.html.erb
  <%= form_with(model: tarea, local: true) do |form| %>
    <% if tarea.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(tarea.errors.count, "error") %> prohibited this tarea from being saved:</h2>

        <ul>
          <% tarea.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :descripcion %>
      <%= form.text_area :descripcion, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :materium_id, "Materia" %>
      <%= form.collection_select :materium_id, @materias, :id, :nombre, include_blank: false, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :estado_id %>
      <%= form.collection_select :estado_id, @estados, :id, :nombre, include_blank: false, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :FechaFin, "Fecha de finalización" %>
      <%=form.date_field :FechaFin %>
    </div>

    <div class="actions">
      <%= form.submit "Guardar", class: "btn btn-primary" %>
    </div>
  <% end %>

app/views/tareas/_navbar.html.erb
<nav class="navbar-wrapper navbar-expand-xl navbar-dark bg-dark" style="{width: 100% !important;}">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuMaterias" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Materias
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuMaterias">
            <%= link_to 'Nueva materia', new_materium_path, class: 'dropdown-item'%>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuEstados" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Estados
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuEstados">
            <%= link_to 'Nuevo estado', new_estado_path, class: 'dropdown-item'%>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuTareas" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Tareas
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuTareas">
            <%= link_to 'Nueva tarea', new_tarea_path, class: 'dropdown-item'%>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuProyecto" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           Proyecto
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuProyecto">
            <%= link_to 'Ver detalles', edit_project_path(@proyecto.id), class: 'dropdown-item'%>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuUsuario" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Usuario
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuUsuario">
            <%= link_to 'Ver cuenta', edit_user_registration_path, class: 'dropdown-item'%>
            <%= link_to 'Cerrar sesión', destroy_user_session_path, :method => :delete , class: 'dropdown-item'%>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <h5 class="navbar-brand"><%= @proyecto.nombre %></h5>
        </li>
      </ul>
    </div>
  </nav>

app/views/tareas/edit.html.erb
<%= stylesheet_link_tag 'comments' %>
<h1>Detalles de la tarea</h1>
<%= link_to 'Volver', tareas_path, class: 'btn btn-primary' %>
<div class="w-75 m-3">
    <%= render 'form', tarea: @tarea %>
    <h3>Comentarios</h3>
  <div class="overflow-auto">
    <%@comentarios.each do |comentario|%>
    <div class="card m-2">
        <div class="card-body">
            <h5 class="card-title"><%=comentario.created_at.localtime.strftime("%d.%m.%Y a las %I:%M%p")%></h5>
            <p class="card-text"><%=comentario.comentario%></p>
        </div>
    </div>
    <% end %>
  </div>
  <%= paginate @comentarios, window: 2 %>
    <%= render partial: 'comments/form' %>
</div>
<%= link_to 'Eliminar esta tarea', tarea_path, method: :delete, data: { confirm: 'No hay vuelta atrás. ¿Seguro?' }, class: 'btn btn-danger' %>

app/views/tareas/index.html.erb
<%= render 'navbar'%>
<div class="table-responsive">
<table class="table mb-0 table-bordered">
  <thead class="thead-dark">
    <tr>
      <th class="text-center">Estados/Materia</th>
      <% @materias.each do |materia|  %>
        <th class="text-center"><%=materia.nombre%></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <%@estados.each do |estado| %>
        <tr>
          <td class="table-primary font-weight-bold justify-content-center"><%=estado.nombre%></td>
          <% @materias.each do |materia|  %>
            <td>
              <% @tareas.each do |tarea| %>
                <% if tarea.estado==estado && tarea.materium==materia %>
                  <div class="card alert-warning" style="width: 18rem;">
                    <div class="card-body">
                      <%= link_to tarea.descripcion, edit_tarea_path(tarea), class: 'alert-link', style: "font-family: 'Coming Soon', cursive; font-size: 18px" %>
                    </div>
                    <%if tarea.FechaFin%>
                      <div class="badge badge-success" style="font-family: 'Coming Soon', cursive; font-size: 18px">FINALIZA: <%=tarea.FechaFin.strftime("%d/%m/%Y")%></div>
                    <%else%>
                      <div class="badge badge-success" style="font-family: 'Coming Soon', cursive; font-size: 18px">Sin fecha definida</div>
                    <%end%>
                  </div><br>
                <% end %>
              <%end%>
            </td>
          <% end %>
        </tr>
    <%end%>
  </tbody>
</table>
</div>

app/views/tareas/new.html.erb
<h1>Nueva tarea</h1>
<div class="p-2">
    <%= render 'form', tarea: @tarea %>
    <%= link_to 'Back', tareas_path %>
</div>

app/views/tareas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripcion:</strong>
  <%= @tarea.descripcion %>
</p>

<p>
  <strong>Materium:</strong>
  <%= @tarea.materium_id %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @tarea.estado_id %>
</p>

<%= link_to 'Edit', edit_tarea_path(@tarea) %> |
<%= link_to 'Back', tareas_path %>